/**
 * Application error codes documented in docs/API_CONTRACT.md §44.
 * Keep these aligned with the API contract wherever errors are surfaced.
 */
export const errorCodes = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  FORBIDDEN: 'FORBIDDEN',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  ACCOUNT_UNVERIFIED: 'ACCOUNT_UNVERIFIED',
  INVALID_OTP: 'INVALID_OTP',
  OWNERSHIP_ERROR: 'OWNERSHIP_ERROR',
  ORGANIZATION_ACCESS_DENIED: 'ORGANIZATION_ACCESS_DENIED',
  PROGRAM_ACCESS_DENIED: 'PROGRAM_ACCESS_DENIED',
  AI_SERVICE_ERROR: 'AI_SERVICE_ERROR',
  AI_OUTPUT_INVALID: 'AI_OUTPUT_INVALID',
  DATABASE_ERROR: 'DATABASE_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;

export type ErrorCode = (typeof errorCodes)[keyof typeof errorCodes] | (string & {});